### ISSUE TITLE
update to bootstrap 3

### ISSUE THREAD

**Issue by jblotus** [sculpin/sculpin-blog-skeleton#28]
will probably work on a pull request for this if you think it's a good idea

**Comment by simensen** [comment]
@jblotus Thanks! There is a theme-aware blog skeleton that uses bootstrap three but it might be time to just update this one. I know other people have been contributing to this skeleton in the meantime so I'd probably accept a PR. :)

**Comment by dbu** [comment]
this can be closed @beryllium , the skeleton uses bootstrap 4.3
