### ISSUE TITLE
Add LICENCE file

### ISSUE THREAD

**Issue by toby-griffiths** [sculpin/sculpin-blog-skeleton#36]
I'm just adding the licence file to my blog & wanted to check on the licensing requirements of this project as I'm using this library to publish my blog.
Do I need to credit the use of this package, or not?  Or actually… am I allowed to use this for my personal blog?  Could I use it for a commercial blog?

**Comment by simensen** [comment]
@toby-griffiths You can consider this blog skeleton to be licensed under MIT. If you'd like to add a LICENSE file to this project via a PR that would be awesome. :) You could copy it from the main sculpin/sculpin project.

https://github.com/sculpin/sculpin-blog-skeleton/blob/master/sculpin.json#L5

Does this satisfy your concerns?

**Comment by toby-griffiths** [comment]
Submitted PR #37

**Comment by simensen** [comment]
@toby-griffiths Great! Thanks!

**Comment by toby-griffiths** [comment]
@simensen Love the quick turn around :o)
