### ISSUE TITLE
Tags and categories pagination are broken

### ISSUE THREAD

**Issue by falvarez** [sculpin/sculpin-blog-skeleton#38]
I have tried setting max_pagination_items: 1 in both tags and categories templates in order to have pagination items generated. Those links are broken. For example, in category "features"

http://localhost:8000/blog/categories/features

"Next page" link is rendered, but it points to http://localhost:8000/blog/categories/2. Shouldn't it point to http://localhost:8000/blog/categories/features/2?

**Comment by WyriHaximus** [comment]
Correct, my temporary workaround is to increase the pagination size: https://github.com/WyriHaximus/blog.wyrihaximus.net/blob/master/app/config/sculpin_kernel.yml#L1-L2 

I've tried to unraffle this issue in the past but I'll revisit it, maybe @simensen has an idea how to fix this?

FYI set my index to a different size though: https://github.com/WyriHaximus/blog.wyrihaximus.net/blob/master/source/index.html#L5-L6

**Comment by falvarez** [comment]
Thank you. I'll stay tuned to this issue. I assume that the issue is related to the skeleton and not to sculpin kernel itself, isn't it?

**Comment by DASPRiD** [comment]
@falvarez nope, definitelly an issue of the kernel.

**Comment by falvarez** [comment]
Thanks for the update :)
