### ISSUE TITLE
github pages 404 error

### ISSUE THREAD

**Issue by michaellenahan** [sculpin/sculpin-blog-skeleton#39]
Hi, I have just created a blog using sculpin-blog-skeleton, and copied the contents of output_prod to my github page.

My blog is here: http://michaellenahan.github.io/index.html

The problem is that here: http://michaellenahan.github.io I get a 404. How can I get index.html to be the default document? Thanks!

**Comment by dragonmantank** [comment]
http://michaellenahan.github.io/ seems to work fine for me. As far as I know Github Pages defaults to `index.html` as the default page.

**Comment by michaellenahan** [comment]
Thanks! It wasn't working for me at first for quite a while. Now it's fixed itself!
