### ISSUE TITLE
Fatal Error with sculpin.phar dependency on PHP 7.0.11

### ISSUE THREAD

**Issue by steverhoades** [sculpin/sculpin-blog-skeleton#43]
```
$ php sculpin.phar install

Fatal error: Cannot use 'String' as class name as it is reserved in phar:///usr/local/docroot/proj/sr-blog/sculpin.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/String.php on line 18
```

**Comment by steverhoades** [comment]
Reference this issue: https://github.com/sculpin/sculpin/issues/297

**Comment by steverhoades** [comment]
Posting this here only because the instructions have the 'If you need Sculpin' section.  Following those directions results in the error described above.

**Comment by WyriHaximus** [comment]
Using sculping.phar isn't the way to go anymore, https://github.com/sculpin/sculpin.io/pull/99 seems we haven't updated the instructions here 🤐

**Comment by steverhoades** [comment]
Unfortunately those directions will not work either without my latest PR to sculpin:
https://github.com/sculpin/sculpin/pull/319
