### ISSUE TITLE
Make skeleton installable with composer create-project

### ISSUE THREAD

**Issue by Xerkus** [sculpin/sculpin-blog-skeleton#47]
Leverage `composer create-project` and composer scripts to make installer package.

**Comment by dbu** [comment]
from how i understand, the only thing needed for this would be to add sculpin/sculpin-blog-skeleton to packagist. @beryllium could you do that please? i will do a pull request to change the readme (also moving more documentation to sculpin.io for consistency)

do you think there would be any useful additional things that should be scripted, @Xerkus ?

**Comment by beryllium** [comment]
Checking with @simensen and @dragonmantank to see what they can do. Not sure if I have the right permissions.

**Comment by beryllium** [comment]
<img width="600" alt="Screen Shot 2019-03-12 at 10 30 13 AM" src="https://user-images.githubusercontent.com/602491/54222056-e0078480-44b1-11e9-896a-80c67d429ace.png">

Because sculpin already exists on Packagist, I don't have permissions to do this.

**Comment by dbu** [comment]
oh, did not know that. seems sane. @simensen or @dragonmantank can you help us out here?

**Comment by WyriHaximus** [comment]
Yeah that added that a few years ago to prevent vendor hijacking. Anyone in the sculpin vendor on packagist has to add it, or add you to an existing package in the sculpin vendor so you can add it

**Comment by beryllium** [comment]
<img width="693" alt="Screen Shot 2019-03-20 at 10 30 29 AM" src="https://user-images.githubusercontent.com/602491/54706022-351f4800-4afb-11e9-9214-7e5f0409e005.png">

**Comment by beryllium** [comment]
Looks like it works now, but it requires the `-s dev` argument for the time being (until 3.0 ships).

**Comment by dbu** [comment]
yay!
